### ISSUE TITLE
Atom Self Link

### ISSUE THREAD

**Issue by sirdemoncze** [bhaktaraz/php-rss-generator#4]
Hello, 

can you add support **Atom Self Link**?

Reference: [https://validator.w3.org/feed/docs/warning/MissingAtomSelfLink.html](https://validator.w3.org/feed/docs/warning/MissingAtomSelfLink.html)

Thank you!

**Comment by bhaktaraz** [comment]
@sirdemoncze you can make changes and create pull request.
