### ISSUE TITLE
Add Image Channel Element

### ISSUE THREAD

**Issue by amiad** [bhaktaraz/php-rss-generator#5]
I tried to use this library but I need image channel.
Please add its.

**Comment by bhaktaraz** [comment]
@amiad you can make changes and create pull request.

**Comment by tenq** [comment]
Hi, I made modifications to generic add custom attributes. If you thing is useful, merge.
[Item.txt](https://github.com/bhaktaraz/php-rss-generator/files/2852125/Item.txt)

**Comment by cloetensbrecht** [comment]
+1 Should be added:
https://validator.w3.org/feed/docs/rss2.html#ltimagegtSubelementOfLtchannelgt

**Comment by cloetensbrecht** [comment]
I created a pull request for this feature:
https://github.com/bhaktaraz/php-rss-generator/pull/11
